# Generated by Django 5.2.17 on 2026-08-26 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("target_url", models.URLField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(auto_now_add=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("processing_since", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "swiftpay_webhook_outbox",
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="swiftpay_we_status_959f9f_idx",
                    )
                ],
            },
        ),
    ]
