# Generated by Django 5.2.17 on 2026-08-26 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', 'Account number must be 9-18 digits')]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$', 'Invalid GST format')]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Invalid IFSC code')]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Invalid PAN format')]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
