# Generated by Django 5.2.17 on 2026-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookoutbox',
            name='processing_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
