# Generated by Django 5.2.17 on 2026-08-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="webhook_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
