# Generated by Django 5.2.17 on 2026-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_alter_merchant_account_number_alter_merchant_gst_and_more'),
        ('payments', '0002_payment_webhook_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('merchant', 'idempotency_key'), name='unique_merchant_idempotency_key'),
        ),
    ]
