# Generated by Django 5.2.17 on 2026-08-09 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('PaymentInitiated', 'Payment Initiated'), ('PaymentAuthorized', 'Payment Authorized'), ('PaymentCaptured', 'Payment Captured'), ('PaymentFailed', 'Payment Failed'), ('PaymentSettled', 'Payment Settled')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_events', to='merchants.merchant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
